default_language_version:
    python: python3.12

repos:
  - repo: local
    hooks:
      - id: python-lints
        name: python-lints
        entry: make pre-commit
        language: system
        types: [python]
