version: "3.9"


x-s3-environment: &x-s3-environment
  MINIO_ROOT_USER: "miniouser"
  MINIO_ROOT_PASSWORD: "miniopassword"
  MINIO_STORAGE_USE_HTTPS: "false"
  BUCKET_NAME: "testbucket"


services:
  s3:
    image: "quay.io/minio/minio:latest"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - s3_data:/data/
      - ./configs/s3/docker-entrypoint.sh:/usr/bin/docker-entrypoint.sh:ro
    environment:
      <<: *x-s3-environment
    command: server /data --console-address ":9090"
    networks:
      app_network:
        aliases:
          - minio.lvh.me


networks:
  app_network:
    external: false

volumes:
  s3_data:
