name: linters

on:
  - pull_request

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: python -m pip install --upgrade pip wheel setuptools poetry
      - name: Run linters & friends
        run: make ci-lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: python -m pip install --upgrade pip wheel setuptools poetry
      - name: Run tests
        run: make ci-test

  pip-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: python -m pip install --upgrade pip wheel setuptools poetry
      - name: Analysing the dependencies with pip-audit
        run: make ci-deps-audit
